// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyzsszgvwgoupaffmjpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5enNzemd2d2dvdXBhZmZtanBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTE5MTIsImV4cCI6MjA3NDI2NzkxMn0._4GwdXDn49B_hZhgH7xjQIYJwYshkfH-XwQPcn9R97o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});